### ISSUE TITLE
nil can't be coerced into Integer

### ISSUE THREAD

**Issue by olafz** [dblock/slack-sup#56]
We set out to try S'Up before we would consider a subscription. Unfortunately, after the first week, S'Up only responded with "nil can't be coerced into Integer" to known commands:

<img width="292" alt="screen shot 2018-04-22 at 11 05 28" src="https://user-images.githubusercontent.com/80709/39093286-1cfde3e6-461d-11e8-803f-e43f80de492e.png">

For unknown commands, it's still friendly enough to say "I don't understand that command!":

<img width="388" alt="screen shot 2018-04-22 at 11 06 24" src="https://user-images.githubusercontent.com/80709/39093291-39f557e0-461d-11e8-9f3e-36824430593d.png">

Needless to say, but just to be sure: it also doesn't schedule triads anymore.

**Comment by dblock** [comment]
```
14:48:08 web.1  | #<TypeError: nil can't be coerced into Integer>
14:48:08 web.1  | /Users/dblock/source/slack/slack-sup/slack-sup/models/stats.rb:22:in `-'
14:48:08 web.1  | /Users/dblock/source/slack/slack-sup/slack-sup/models/stats.rb:22:in `reported_outcomes_count'
14:48:08 web.1  | /Users/dblock/source/slack/slack-sup/slack-sup/commands/stats.rb:26:in `block in <class:Stats>'
14:48:08 web.1  | /Users/dblock/source/slack/slack-sup/slack-sup/commands/mixins/subscribe.rb:14:in `block in subscribe_command'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/slack-ruby-bot-0.10.4/lib/slack-ruby-bot/commands/base.rb:71:in `block in invoke'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/slack-ruby-bot-0.10.4/lib/slack-ruby-bot/commands/base.rb:56:in `each_pair'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/slack-ruby-bot-0.10.4/lib/slack-ruby-bot/commands/base.rb:56:in `invoke'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/slack-ruby-bot-server-0.6.1/lib/slack-ruby-bot-server/ext/mongoid/slack-ruby-bot/commands/base.rb:8:in `invoke'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/slack-ruby-bot-0.10.4/lib/slack-ruby-bot/hooks/message.rb:7:in `block in call'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/slack-ruby-bot-0.10.4/lib/slack-ruby-bot/hooks/message.rb:7:in `each'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/slack-ruby-bot-0.10.4/lib/slack-ruby-bot/hooks/message.rb:7:in `detect'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/slack-ruby-bot-0.10.4/lib/slack-ruby-bot/hooks/message.rb:7:in `call'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/slack-ruby-bot-0.10.4/lib/slack-ruby-bot/hooks/set.rb:33:in `block (2 levels) in register_callback'
14:48:08 web.1  | /Users/dblock/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/set.rb:324:in `each_key'
14:48:08 web.1  | /Users/dblock/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/set.rb:324:in `each'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/slack-ruby-bot-0.10.4/lib/slack-ruby-bot/hooks/set.rb:32:in `block in register_callback'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/slack-ruby-client-0.9.0/lib/slack/real_time/client.rb:198:in `block in run_callbacks'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/slack-ruby-client-0.9.0/lib/slack/real_time/client.rb:197:in `each'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/slack-ruby-client-0.9.0/lib/slack/real_time/client.rb:197:in `run_callbacks'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/slack-ruby-client-0.9.0/lib/slack/real_time/client.rb:178:in `dispatch'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/slack-ruby-client-0.9.0/lib/slack/real_time/client.rb:93:in `block (2 levels) in run_loop'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:39:in `block in emit'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `each'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `emit'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/websocket-driver-0.6.5/lib/websocket/driver/hybi.rb:396:in `emit_message'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/websocket-driver-0.6.5/lib/websocket/driver/hybi.rb:379:in `emit_frame'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/websocket-driver-0.6.5/lib/websocket/driver/hybi.rb:123:in `parse'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/websocket-driver-0.6.5/lib/websocket/driver/client.rb:63:in `parse'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/slack-ruby-client-0.9.0/lib/slack/real_time/concurrency/celluloid.rb:57:in `handle_read'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
14:48:08 web.1  | /Users/dblock/.rvm/gems/ruby-2.4.1/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by dblock** [comment]
Sorry about that @olafz. This was a bug.

* Can you please check whether `stats` now reports results and that the error is gone?
* I made a change that should let you try things out for another two weeks, so you don't need to upgrade immediately. Hope you like the bot enough then :)

Let me know how it goes? Feel free to reach out to dblock[at]dblock[dot]org.

**Comment by olafz** [comment]
Hi @dblock,

It works again! Thanks for extending the trial; we'll go agin this week ;)
